export enum CharacterName {
  Aura = "Aura",
  Denken = "Denken",
  Edel = "Edel",
  Fern = "Fern",
  Flamme = "Flamme",
  Frieren = "Frieren",
  Himmel = "Himmel",
  Laufen = "Laufen",
  Linie = "Linie",
  Methode = "Methode",
  Sein = "Sein",
  Sense = "Sense",
  Serie = "Serie",
  Stark = "Stark",
  Stille = "Stille",
  Ubel = "Übel",
  Wirbel = "Wirbel",
}
