export enum CharacterName {
  Denken = "Denken",
  Edel = "Edel",
  Fern = "Fern",
  Frieren = "Frieren",
  Himmel = "Himmel",
  Laufen = "Laufen",
  Linie = "Linie",
  Sein = "Sein",
  Sense = "Sense",
  Serie = "Serie",
  Stark = "Stark",
  Stille = "Stille",
  Ubel = "Übel",
}